### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by cameronFarley** [CSAllenISD/2023-ISP-AutomatedAttendance#16]
Creating a Gantt Chart will help keep our team working efficiently and moving in the right direction. It will also allow us to plan out our thought and specific components of the project we will have to focus on.

**Comment by Bread21234** [comment]
The Gantt chart is complete and can be found here. I will update the dates as time goes on and we discover how much time things will take. It is also in the discord server if that is easier to look at. If you have any questions, let me know.

https://docs.google.com/spreadsheets/d/15uGPTuBVmWsWW6YNMRo7OjLgvPd4dv3nIHc8Ax7pDAY/edit?usp=drive_web&ouid=114248342926399370310
