### ISSUE TITLE
Link camera to program

### ISSUE THREAD

**Issue by cameronFarley** [CSAllenISD/2023-ISP-AutomatedAttendance#17]
We will need to find a way through the backdoor to allow our program to "see" using a camera. This will allow for facial recognition and updating our data tables.

**Comment by ayaank13** [comment]
Wow very good 100%

**Comment by Bread21234** [comment]
I have a few ideas on how to do this. We may need to use an API. I will begin research.

**Comment by Bread21234** [comment]
At the moment, the camera works as input in its own program. Now, we need to embed the code that uses the camera on the website for further use. If possible, experiment with the quality of images the camera can take without slowing down the program too much.
