### ISSUE TITLE
Make sure all files are backed up to github

### ISSUE THREAD

**Issue by ayaank13** [CSAllenISD/2023-ISP-AutomatedAttendance#25]

**Comment by Oliver-Hankins** [comment]
I think that we should really try to stay on a schedule and make sure that we back up everything to Github so that in case anything goes wrong, we can revert back to a previous version and continue working.

**Comment by joshuawlee** [comment]
I agree that making sure all files are back up to github is a crucial step in succeeding as there is always a possibility in having to revert back to previous commits as this is a big project.
