### ISSUE TITLE
Research Python Libraries for Facial Recognition

### ISSUE THREAD

**Issue by AkshayVemulapalli** [CSAllenISD/2023-ISP-AutomatedAttendance#26]
Also research transfer learning for image recognition because that's probably what we are going to use.

**Comment by VJCS185** [comment]
Yeah, that's a good idea. We should definitely implement this into our project.

**Comment by Bread21234** [comment]
Some of the databases that are going to be used are as follows: face_recognition, os, sys, cv2, numpy, and math. These databases will work concurrently in order to implement facial recognition.

**Comment by RusticKnite** [comment]
Research as been done with documentation in Connor's and Josh's playground branch. Actual current facial recognition is used in development.
