### ISSUE TITLE
Make camera recognize a face is in frame

### ISSUE THREAD

**Issue by Bread21234** [CSAllenISD/2023-ISP-AutomatedAttendance#30]

**Comment by cameronFarley** [comment]
Yes, baby steps is important to break down bigger tasks

**Comment by VJCS185** [comment]
Yeah, this will be crucial for our project.

**Comment by Serenity-Underwood** [comment]
Question: How are we going to project the facial recognition proportion? Do you want it where the teacher takes a picture of the class (our faces first before having the whole class), or do you want it where the students click a link to the website and take their own attendance on the computer? I would think it would be better to have just one person take a picture to get everyone's faces, but if we do it individually, that can potentially prevent quality issues.

**Comment by Bread21234** [comment]
https://github.com/CSAllenISD/2023-ISP-AutomatedAttendance/issues/30#issuecomment-1382669779

If you check the github, you will see the python resources we are using to implement facial recognition. Also to answer your question, students do not log in or click anything themselves. Rather, they simply walk past a camera in order to check in on the teacher's account. The camera will be running during the allotted time and it will automate the process.

**Comment by Bread21234** [comment]
The python portion is able to recognize faces. However, the facial recognition is not yet implemented into the website.
