### ISSUE TITLE
Create an early database with only our faces before we extend it to data from the whole class.

### ISSUE THREAD

**Issue by AkshayVemulapalli** [CSAllenISD/2023-ISP-AutomatedAttendance#32]
Use the laptop camera to take pictures of our faces from a few different angles. We will use the laptop camera at first for the MVP, and then maybe move to another camera later

**Comment by Oliver-Hankins** [comment]
I think this will be essential for testing our product later on in the project. This process might also be similar to the way that apple uses face ID for iPhones.

**Comment by RusticKnite** [comment]
Related to other issues and already done. We are now moving on to making the picture account database.
