### ISSUE TITLE
Training and Testing Data

### ISSUE THREAD

**Issue by VJCS185** [CSAllenISD/2023-ISP-AutomatedAttendance#35]
We need to make sure to get data on faces from the angle that the camera will be at to increase the accuracy of the model. We also need to make sure to get lots of pictures of the faces we are trying to scan.

**Comment by joshuawlee** [comment]
I believe the idea of getting different angles on faces is a great idea in improving accuracy of our program, however, it may be difficult to test many different angles as the picture provided to us for attendance is typically from the same basic photo ID angle.

**Comment by AkshayVemulapalli** [comment]
It might be fine to only use a few angles, if we are able to get people to stand at a certain place and look at the camera.
