### ISSUE TITLE
Purchase/acquire a camera

### ISSUE THREAD

**Issue by joshuawlee** [CSAllenISD/2023-ISP-AutomatedAttendance#37]
We need to make sure we purchase/acquire a camera that will be within a reasonable price range and also easy to work with.

**Comment by Serenity-Underwood** [comment]
Question: Could we possibly find permissions to the access that the device has already?

**Comment by AkshayVemulapalli** [comment]
I think that for the minimum viable product we should just use a laptop camera, but we can upgrade to a better camera after we finish making the other features that we need for a minimum viable product.

**Comment by cameronFarley** [comment]
We will be using a laptop camera, no need to spend money for an external camera

**Comment by RusticKnite** [comment]
Issue Resolved as we are using a camera that is already integrated into the computer system. We don't need to use an external camera for our final release of our project.
