### ISSUE TITLE
Research and create a system to make multiple accounts.

### ISSUE THREAD

**Issue by Bread21234** [CSAllenISD/2023-ISP-AutomatedAttendance#44]

**Comment by Bread21234** [comment]
Design a system where there can be multiple different users with different information pertaining to them. Utilizing a username and password, allow a user to log in and view each of their classes separately from another user. There should be a login page followed by a greeting. Once logged in, the app should display the classes the user has previously made, meaning progress is SAVED.

**Comment by AkshayVemulapalli** [comment]
The database we create should have an entry for each account that is made in the system. For each account (teacher), the database should store what classes/periods they teach, and what students are enrolled in each class/period. The database should be able to easily be updated over time to accommodate changing classes, teachers, and students.
