### ISSUE TITLE
Create an API 

### ISSUE THREAD

**Issue by joshuawlee** [CSAllenISD/2023-ISP-AutomatedAttendance#46]
We will create an API to allow for multiple instances of the product to be able to run simultaneously while sharing a common database. This will allow for our product to be viable in an environment that requires the attendance of multiple groups of people, such as a school or office.

**Comment by joshuawlee** [comment]
Due to time constraints we will be classifying this task as a "want" more than a need, meaning that we will be creating an API after we have accomplished all of our "needs". This is due to the fact that our product doesn't necessarily need an API to function.

**Comment by RusticKnite** [comment]
We used Flask instead of an API. But Flask takes care of what the API does and more for our project, so it was a better implementation for our project.
