### ISSUE TITLE
Create CSS Files

### ISSUE THREAD

**Issue by joshuawlee** [CSAllenISD/2023-ISP-AutomatedAttendance#47]
Creating CSS files will allow us to create a well organized, visually appealing, functional, and consistent front end. Through the use of CSS files, our code will be cleaned up, which allows for an easier time programming and reading / understanding the code.

**Comment by VJCS185** [comment]
We should also create the CSS file in a way that reduces clutter on the website. This can be done by using a common theme throughout the entire application to reduce confusion, minimize the number of buttons on each screen, and have a description of the buttons' function when the cursor is left over the button for an extended period of time. Doing these things will make sure the teachers are not slowed down by the website itself so the goal of saving time in each period is achieved.

**Comment by AkshayVemulapalli** [comment]
I think that one thing we should decide on beforehand is a color scheme for the website. This will allow the CSS files to be organized, and ensure that the website/application has a consistent and clean look. Once, we decide the color scheme, the front-end developers can start designing/coding the pages for the website.
