### ISSUE TITLE
Create an Account System

### ISSUE THREAD

**Issue by joshuawlee** [CSAllenISD/2023-ISP-AutomatedAttendance#48]
Creating an account system will be a crucial feature for our product as this will allow for multiple group managers (teachers, managers, bosses, etc.) to each have their own collective groups (such as classes, teams, etc.). This will allow our UI to be user friendly as each user will be able to manage their own groups. This system will function with our website by using a database to store user data (username, password, classes, etc.)

**Comment by Oliver-Hankins** [comment]
Account System has been initialized
