### ISSUE TITLE
Allow teachers to manually update attendance.

### ISSUE THREAD

**Issue by Bread21234** [CSAllenISD/2023-ISP-AutomatedAttendance#51]
In the event of an error or an excused late pass (from a counselor or something), allow a teacher to manually edit attendance.

**Comment by VJCS185** [comment]
We can do this in a few ways. We can have a page on the automated attendance application that allows a teacher to place a request for an attendance change for a particular student and an attendance clerk can see the request and manually make the change in the system. Another way this can be done it giving all teachers direct access to the system allowing them to just manually make the change immediately from their computer.

**Comment by Bread21234** [comment]
redundant issue
