### ISSUE TITLE
Create a Log In / Sign Up Page

### ISSUE THREAD

**Issue by joshuawlee** [CSAllenISD/2023-ISP-AutomatedAttendance#54]
This page will tie into our account system as any user that creates a new account will be stored in our account system and given the opportunity to take attendance for the classes / groups they create on their account after logging in. This page should be made with a minimalistic and simple UI so that even substitute teachers will be able to navigate the system without any difficulties.

**Comment by VJCS185** [comment]
The login and signup page should also ensure that the person signing up is part of a legitimate school or class-taught system. This will make sure only teachers are able to use this software which will make sure the system is not overloaded by new users and requests like ChatGPT.
