### ISSUE TITLE
Integrate the Website with an external camera

### ISSUE THREAD

**Issue by AkshayVemulapalli** [CSAllenISD/2023-ISP-AutomatedAttendance#60]
As we near the stages towards our final product, adding an external camera would be a way to make the system more user friendly. For the minimum viable product, we will likely just use a laptop webcam as the camera that the students will have to walk up to, but using an external camera could give us more options such as allowing us to place the camera on the outside of the door so that it automatically scans students as they walk in.

**Comment by RusticKnite** [comment]
Too similar to issue #71 refer to this issue for reference and further documentation.
