### ISSUE TITLE
Make the system give a detention to students who have a number of absences or tardies that is too high.

### ISSUE THREAD

**Issue by VJCS185** [CSAllenISD/2023-ISP-AutomatedAttendance#62]
The detention should be assigned to the student in the system and it should automatically send the student an email notifying them of the detention they have received. The detention should be removed from the system when the student is recognized by the system to be going into a room designated for detentions.

**Comment by RusticKnite** [comment]
We decided that it won't be used in the final release of the project because it isn't vital for the final project. Will label accordingly.
