### ISSUE TITLE
implement facial recognition within html utilizing flask

### ISSUE THREAD

**Issue by Bread21234** [CSAllenISD/2023-ISP-AutomatedAttendance#66]
https://stackoverflow.com/questions/62255949/face-detection-using-webhtml-css-and-python

use this resource.
Render the page using flask and utilize external python file.

**Comment by joshuawlee** [comment]
https://web.dev/getusermedia-intro/ 

link to implement video and audio in HTML5

https://towardsdatascience.com/video-streaming-in-web-browsers-with-opencv-flask-93a38846fe00

link to video capture & video streaming in Web Browsers with Flask
